# Generated by Django 5.2.7 on 2025-12-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_questionattempt_timestamp_questionattempt_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='The question or concept')),
                ('back', models.TextField(help_text='The answer or definition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.studymaterial')),
            ],
        ),
    ]
